[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.6"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.16.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.6"

[[override]]
  name = "k8s.io/kube-scheduler"
  version = "kubernetes-1.16.6"

[[constraint]]
  name = "k8s.io/kubernetes"
  # version = "v1.16.6"
  revision = "72c30166b2105cd7d3350f2c28a219e6abcd79eb"

[[override]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.2"

[[override]]
  name = "sigs.k8s.io/structured-merge-diff"
  revision = "978ad1ec166f83b8380e28ec8b8d7cecca0bd01d"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "743ec37842bffe49dd4221d9026f30fb1d5adbc4"

[[override]]
  name = "k8s.io/csi-translation-lib"
  version = "kubernetes-1.16.6"

[[override]]
  name = "github.com/coreos/etcd"
  revision = "v3.3.17"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "kubernetes-1.16.6"

[[override]]
  name = "google.golang.org/grpc"
  revision = "v1.23.0"

[prune]
  go-tests = true
  unused-packages = true
